apiVersion: v1
kind: Service
metadata:
  name: custombuild-service
spec:
  selector:
    app: custumbuild
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30089

